---


# 4. Use Ansible to restore your 'primary Ethernet interface' back to the following state (or your secondary interface depending on which one you used):

# description:                    <none>
# switchport mode:           access
# access VLAN:                1
# trunk allowed VLANs:    all

# Also use Ansible to remove the three VLANs that you configured.


- name: Clean up Arista Trunk Interface by Claudia
  hosts: arista
  gather_facts: False

  tasks:
    - name: Default Interface
      eos_config: command="default interface Ethernet6"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      register: int_output

    - debug: var=int_output  

    - name: Remove Vlans
      eos_config: command="no vlan {{ item }}"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      with_items:
        - 991
        - 992
        - 993
        - 994

